In [23]:
# impoerting libraries
import numpy as np

In [24]:
print("\n---ARRAY CREATION ---")

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)

print("Zeros:", np.zeros(5))
print("Ones:", np.ones(5))
print("Full:", np.full(5, 7))
print("Arange:", np.arange(1, 11))
print("Linspace:", np.linspace(1, 10, 5))


---ARRAY CREATION ---
Array: [10 20 30 40 50]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Full: [7 7 7 7 7]
Arange: [ 1  2  3  4  5  6  7  8  9 10]
Linspace: [ 1.    3.25  5.5   7.75 10.  ]


In [25]:

print("\n---ARRAY PROPERTIES ---")

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Array:\n", arr)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Item size:", arr.itemsize)


---ARRAY PROPERTIES ---
Array:
 [[10 20 30]
 [40 50 60]]
Dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64
Item size: 8


In [26]:
print("\n---AXIS ---")

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Array:\n", arr)

print("Column-wise sum (axis=0):", np.sum(arr, axis=0))
print("Row-wise sum (axis=1):", np.sum(arr, axis=1))

print("Column-wise mean:", np.mean(arr, axis=0))
print("Row-wise mean:", np.mean(arr, axis=1))


---AXIS ---
Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Column-wise sum (axis=0): [120 150 180]
Row-wise sum (axis=1): [ 60 150 240]
Column-wise mean: [40. 50. 60.]
Row-wise mean: [20. 50. 80.]


In [27]:
print("\n---INDEXING ---")

arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Third element:", arr[2])

arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("First row:", arr2[0])
print("Second column:", arr2[:, 1])
print("Element at row 2, column 3:", arr2[1, 2])


---INDEXING ---
First element: 10
Last element: 50
Third element: 30
First row: [10 20 30]
Second column: [20 50]
Element at row 2, column 3: 60


In [28]:
print("\n--- SLICING ---")

arr = np.arange(10, 51)

print("Array:", arr)
print("First 3:", arr[:3])
print("Last 3:", arr[-3:])
print("Every second element:", arr[::2])
print("Index 2 to 6:", arr[2:7])


--- SLICING ---
Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
First 3: [10 11 12]
Last 3: [48 49 50]
Every second element: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Index 2 to 6: [12 13 14 15 16]


In [29]:
print("\n--- BOOLEAN INDEXING ---")

marks = np.array([45, 78, 92, 35, 67, 88, 56, 95])

print("Marks:", marks)

print("Marks > 60:", marks[marks > 60])
print("Marks < 50:", marks[marks < 50])
print("Marks between 50 and 80:",
      marks[(marks >= 50) & (marks <= 80)])


--- BOOLEAN INDEXING ---
Marks: [45 78 92 35 67 88 56 95]
Marks > 60: [78 92 67 88 95]
Marks < 50: [45 35]
Marks between 50 and 80: [78 67 56]


In [30]:
print("\n--- DATA TYPE CONVERSION ---")

arr = np.array([10, 20, 30, 40])

print("Original:", arr)
print("Original type:", arr.dtype)

float_arr = arr.astype(float)

print("Float array:", float_arr)
print("New type:", float_arr.dtype)

string_arr = arr.astype(str)

print("String array:", string_arr)
print("New type:", string_arr.dtype)



--- DATA TYPE CONVERSION ---
Original: [10 20 30 40]
Original type: int64
Float array: [10. 20. 30. 40.]
New type: float64
String array: ['10' '20' '30' '40']
New type: <U21


In [31]:
print("\n--- MATHEMATICAL OPERATIONS ---")

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

print("np.add():", np.add(a, b))
print("np.subtract():", np.subtract(a, b))
print("np.multiply():", np.multiply(a, b))
print("np.divide():", np.divide(a, b))

print("Square root:", np.sqrt(a))


--- MATHEMATICAL OPERATIONS ---
Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]
np.add(): [12 24 35 48]
np.subtract(): [ 8 16 25 32]
np.multiply(): [ 20  80 150 320]
np.divide(): [5. 5. 6. 5.]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532]


In [32]:

print("\n--- STATISTICAL FUNCTIONS ---")

marks = np.array([45, 78, 92, 35, 67, 88, 56, 95])

print("Marks:", marks)
print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Standard deviation:", np.std(marks))
print("Variance:", np.var(marks))


--- STATISTICAL FUNCTIONS ---
Marks: [45 78 92 35 67 88 56 95]
Sum: 556
Mean: 69.5
Median: 72.5
Minimum: 35
Maximum: 95
Standard deviation: 21.065374432940896
Variance: 443.75


In [33]:
print("\n---  NaN AND SPECIAL VALUES ---")

arr = np.array([10, 20, np.nan, 40, np.inf, 60])

print("Array:", arr)

print("NaN positions:", np.isnan(arr))
print("Infinite positions:", np.isinf(arr))

valid_values = arr[~np.isnan(arr) & ~np.isinf(arr)]

print("Valid values:", valid_values)
print("Mean of valid values:", np.mean(valid_values))


---  NaN AND SPECIAL VALUES ---
Array: [10. 20. nan 40. inf 60.]
NaN positions: [False False  True False False False]
Infinite positions: [False False False False  True False]
Valid values: [10. 20. 40. 60.]
Mean of valid values: 32.5


In [34]:

print("\n--- RESHAPING ---")

arr = np.arange(1, 13)

print("Original:", arr)

print("2 x 6:\n", arr.reshape(2, 6))
print("3 x 4:\n", arr.reshape(3, 4))
print("4 x 3:\n", arr.reshape(4, 3))

matrix = arr.reshape(3, 4)

print("Flatten:", matrix.flatten())
print("Ravel:", matrix.ravel())

print("Transpose:\n", matrix.transpose())


--- RESHAPING ---
Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2 x 6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
3 x 4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4 x 3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [35]:
print("\n--- COMBINING ARRAYS ---")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Concatenate:", np.concatenate((a, b)))

print("Vertical stack:")
print(np.vstack((a, b)))

print("Horizontal stack:")
print(np.hstack((a, b)))

print("Stack:")
print(np.stack((a, b)))


--- COMBINING ARRAYS ---
Concatenate: [1 2 3 4 5 6]
Vertical stack:
[[1 2 3]
 [4 5 6]]
Horizontal stack:
[1 2 3 4 5 6]
Stack:
[[1 2 3]
 [4 5 6]]


In [36]:
print("\n--- SPLITTING ARRAYS ---")

arr = np.arange(1, 13)

print("Array:", arr)

print("2 parts:")
print(np.split(arr, 2))

print("3 parts:")
print(np.split(arr, 3))

print("Array split into 5 parts:")
print(np.array_split(arr, 5))


--- SPLITTING ARRAYS ---
Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2 parts:
[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]
3 parts:
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
Array split into 5 parts:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]


In [37]:
print("\n--- SORTING AND SEARCHING ---")

arr = np.array([50, 20, 80, 10, 40, 80, 30])

print("Original:", arr)
print("Sorted:", np.sort(arr))
print("Argsort:", np.argsort(arr))
print("Maximum position:", np.argmax(arr))
print("Minimum position:", np.argmin(arr))
print("Unique values:", np.unique(arr))


--- SORTING AND SEARCHING ---
Original: [50 20 80 10 40 80 30]
Sorted: [10 20 30 40 50 80 80]
Argsort: [3 1 6 4 0 2 5]
Maximum position: 2
Minimum position: 3
Unique values: [10 20 30 40 50 80]


In [38]:
print("\n--- WHERE ---")

marks = np.array([45, 78, 92, 35, 67, 88, 40])

result = np.where(marks >= 50, "Pass", "Fail")

print("Marks:", marks)
print("Result:", result)


--- WHERE ---
Marks: [45 78 92 35 67 88 40]
Result: ['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail']


In [39]:
print("\n--- BROADCASTING ---")

arr = np.array([10, 20, 30, 40])

print("Original:", arr)
print("After adding 5:", arr + 5)

matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])

values = np.array([1, 2, 3])

print("Matrix:\n", matrix)
print("Values:", values)
print("Broadcasting result:\n", matrix + values)


--- BROADCASTING ---
Original: [10 20 30 40]
After adding 5: [15 25 35 45]
Matrix:
 [[10 20 30]
 [40 50 60]]
Values: [1 2 3]
Broadcasting result:
 [[11 22 33]
 [41 52 63]]


In [40]:
print("\n--- RANDOM NUMBERS ---")

np.random.seed(42)

print("Random integers:")
print(np.random.randint(1, 101, 10))

print("Random 3 x 3 array:")
print(np.random.rand(3, 3))

print("Random normal values:")
print(np.random.randn(5))


--- RANDOM NUMBERS ---
Random integers:
[52 93 15 72 61 21 83 87 75 75]
Random 3 x 3 array:
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Random normal values:
[ 0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112]
